apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mykinds.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: Mykind
    listKind: MykindList
    plural: mykinds
    singular: mykind
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
