apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-operator-ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-operator-ansible
  template:
    metadata:
      labels:
        name: memcached-operator-ansible
    spec:
      serviceAccountName: memcached-operator-ansible
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: quay.io/btenneti/memcached-operator-ansible:v0.0.6
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: quay.io/btenneti/memcached-operator-ansible:v0.0.6
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memcached-operator-ansible"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
